# -*- coding: utf-8 -*-
"""FinancialData Usage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/SOME_ID
"""

!pip install --upgrade gdrive

from google.colab import drive
drive.mount('/content/drive')

!ls -lah /content/drive/MyDrive/

!mkdir /content/DuckDB

!rsync  -ah --progress /content/drive/MyDrive/DuckDB/FinancialData/FinanceData.db /content/DuckDB

# Commented out IPython magic to ensure Python compatibility.
# Install/update the necessary extensions
!pip install --quiet jupysql duckdb-engine

# Load the SQL extension and connect to DuckDB database
# %load_ext sql
# %config SqlMagic.autopandas = True
# %sql duckdb:////content/DuckDB/FinanceData.db

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext sql

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# ROLLBACK;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM duckdb_tables();

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_account_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_customer_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_ledger_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_loan_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_transaction_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %config SqlMagic.autocommit = True
# %sql --close duckdb:////content/DuckDB/FinanceData.db

import duckdb

target_schema = "aws_project"

# Connection automatically opens and safely closes using 'with'
with duckdb.connect("/content/DuckDB/FinanceData.db") as conn:
    query = f"""
        SELECT table_name, sql
        FROM duckdb_tables()
        WHERE schema_name = '{target_schema}' AND sql IS NOT NULL
    """
    results = conn.execute(query).fetchall()

    for table_name, create_sql in results:
        print(f"--- Table: {target_schema}.{table_name} ---")
        print(create_sql)
        print("\n" + "=" * 50 + "\n")

print("Database connection closed automatically.")

# Commented out IPython magic to ensure Python compatibility.
import duckdb

# 1. Connect using Python
conn = duckdb.connect("/content/DuckDB/FinanceData.db")

# 2. Set up SQL magic
# %load_ext sql
# %config SqlMagic.autopandas = True

# 3. Pass the active 'conn' object straight to the magic command
# %sql conn

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext sql

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q1:
# SELECT
#     c.customer_id,
#     c.first_name,
#     c.last_name,
#     COUNT(t.transaction_id) AS total_transactions
# FROM aws_project.finance_customer_data_stg AS c
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.customer_id = c.customer_id
# JOIN aws_project.finance_transaction_data_stg AS t
#     ON t.src_account_id = a.account_id
# WHERE
#     t.transaction_date >= CURRENT_DATE - INTERVAL 5 YEAR
# GROUP BY
#     c.customer_id,
#     c.first_name,
#     c.last_name
# ORDER BY
#     total_transactions DESC
# LIMIT
#     5;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q2:
# SELECT
#     COUNT(DISTINCT l.customer_id) AS loan_and_account_customers
# FROM aws_project.finance_loan_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON l.customer_id = a.customer_id
# WHERE
#     a.acc_opening_date <= l.start_date;-- 15,88,272

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- TEST
# SELECT
#   COUNT(*)
# FROM aws_project.finance_customer_data_stg;-- 50,00,000

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- TEST
# SELECT
#     COUNT(DISTINCT l.customer_id) AS loan_and_account_customers
# FROM aws_project.finance_loan_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON l.customer_id = a.customer_id
# WHERE
#     a.acc_opening_date > l.start_date;-- 17,55,118
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- TEST
# SELECT
#     COUNT(DISTINCT c.customer_id) AS no_loan_accounts_customers
# FROM aws_project.finance_customer_data_stg AS c
# LEFT OUTER JOIN aws_project.finance_loan_data_stg AS l
#     ON l.customer_id = c.customer_id
# WHERE
#     l.customer_id IS NULL;-- 49,96,843

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- TEST
# SELECT
#     COUNT(DISTINCT c.customer_id) AS no_loan_accounts_customers
# FROM aws_project.finance_customer_data_stg AS c
# LEFT OUTER JOIN aws_project.finance_loan_data_stg AS l
#     ON l.customer_id = c.customer_id
# WHERE
#     l.customer_id IS NOT NULL;-- 3,151

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q2 (new):
# SELECT
#     COUNT(DISTINCT l.customer_id) AS loan_and_account_customers
# FROM aws_project.finance_loan_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON l.customer_id = a.customer_id
# JOIN aws_project.finance_customer_data_stg AS c-- We must have record here
#     ON c.customer_id = l.customer_id
# WHERE
#     a.acc_opening_date <= l.start_date;-- 2,028

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q3:
# 
# SELECT DISTINCT
#     c.customer_id,
#     c.first_name,
#     c.last_name,
#     c.email,
#     a.acc_opening_date
# FROM aws_project.finance_customer_data_stg AS c
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.customer_id = c.customer_id
# WHERE
#     a.acc_opening_date <= CURRENT_DATE - INTERVAL 5 YEAR;-- 12,192

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q4:
# 
# SELECT
#     currency_code,
#     SUM(CASE WHEN tran_status = 'TranStatus.C' THEN 1 ELSE 0 END) AS completed_count,
#     SUM(CASE WHEN tran_status = 'TranStatus.F' THEN 1 ELSE 0 END) AS failed_count
# FROM aws_project.finance_transaction_data_stg
# GROUP BY
#     currency_code
# ORDER BY
#     completed_count DESC,
#     failed_count DESC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT
#   DISTINCT tran_status
# FROM aws_project.finance_transaction_data_stg;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT
#   currency_code
#   , tran_status
#   , COUNT(tran_status)
# FROM aws_project.finance_transaction_data_stg
# GROUP BY
#   currency_code
#   , tran_status
