# -*- coding: utf-8 -*-
"""FinancialData Usage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/SOME_ID
"""

!pip install --upgrade gdrive

from google.colab import drive
drive.mount('/content/drive')

!ls -lah /content/drive/MyDrive/

!mkdir /content/DuckDB

!rsync  -ah --progress /content/drive/MyDrive/DuckDB/FinancialData/FinanceData.db /content/DuckDB

# Commented out IPython magic to ensure Python compatibility.
# Install/update the necessary extensions
!pip install --quiet jupysql duckdb-engine

# Load the SQL extension and connect to DuckDB database
# %load_ext sql
# %config SqlMagic.autopandas = True
# %sql duckdb:////content/DuckDB/FinanceData.db

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext sql

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# ROLLBACK;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM duckdb_tables();

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_account_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_customer_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_ledger_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_loan_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#   *
# FROM pragma_table_info('aws_project.finance_transaction_data_stg');

# Commented out IPython magic to ensure Python compatibility.
# %config SqlMagic.autocommit = True
# %sql --close duckdb:////content/DuckDB/FinanceData.db

import duckdb

target_schema = "aws_project"

# Connection automatically opens and safely closes using 'with'
with duckdb.connect("/content/DuckDB/FinanceData.db") as conn:
    query = f"""
        SELECT table_name, sql
        FROM duckdb_tables()
        WHERE schema_name = '{target_schema}' AND sql IS NOT NULL
    """
    results = conn.execute(query).fetchall()

    for table_name, create_sql in results:
        print(f"--- Table: {target_schema}.{table_name} ---")
        print(create_sql)
        print("\n" + "=" * 50 + "\n")

print("Database connection closed automatically.")

# Commented out IPython magic to ensure Python compatibility.
import duckdb

# 1. Connect using Python
conn = duckdb.connect("/content/DuckDB/FinanceData.db")

# 2. Set up SQL magic
# %load_ext sql
# %config SqlMagic.autopandas = True

# 3. Pass the active 'conn' object straight to the magic command
# %sql conn

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext sql

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q1:
# SELECT
#     c.customer_id,
#     c.first_name,
#     c.last_name,
#     COUNT(t.transaction_id) AS total_transactions
# FROM aws_project.finance_customer_data_stg AS c
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.customer_id = c.customer_id
# JOIN aws_project.finance_transaction_data_stg AS t
#     ON t.src_account_id = a.account_id
# WHERE
#     t.transaction_date >= CURRENT_DATE - INTERVAL 5 YEAR
# GROUP BY
#     c.customer_id,
#     c.first_name,
#     c.last_name
# ORDER BY
#     total_transactions DESC
# LIMIT
#     5;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q2:
# SELECT
#     COUNT(DISTINCT l.customer_id) AS loan_and_account_customers
# FROM aws_project.finance_loan_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON l.customer_id = a.customer_id
# WHERE
#     a.acc_opening_date <= l.start_date;-- 15,88,272

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- TEST
# SELECT
#   COUNT(*)
# FROM aws_project.finance_customer_data_stg;-- 50,00,000

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- TEST
# SELECT
#     COUNT(DISTINCT l.customer_id) AS loan_and_account_customers
# FROM aws_project.finance_loan_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON l.customer_id = a.customer_id
# WHERE
#     a.acc_opening_date > l.start_date;-- 17,55,118
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- TEST
# SELECT
#     COUNT(DISTINCT c.customer_id) AS no_loan_accounts_customers
# FROM aws_project.finance_customer_data_stg AS c
# LEFT OUTER JOIN aws_project.finance_loan_data_stg AS l
#     ON l.customer_id = c.customer_id
# WHERE
#     l.customer_id IS NULL;-- 49,96,843

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- TEST
# SELECT
#     COUNT(DISTINCT c.customer_id) AS no_loan_accounts_customers
# FROM aws_project.finance_customer_data_stg AS c
# LEFT OUTER JOIN aws_project.finance_loan_data_stg AS l
#     ON l.customer_id = c.customer_id
# WHERE
#     l.customer_id IS NOT NULL;-- 3,151

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q2 (new):
# SELECT
#     COUNT(DISTINCT l.customer_id) AS loan_and_account_customers
# FROM aws_project.finance_loan_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON l.customer_id = a.customer_id
# JOIN aws_project.finance_customer_data_stg AS c-- We must have record here
#     ON c.customer_id = l.customer_id
# WHERE
#     a.acc_opening_date <= l.start_date;-- 2,028

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q3:
# 
# SELECT DISTINCT
#     c.customer_id,
#     c.first_name,
#     c.last_name,
#     c.email,
#     a.acc_opening_date
# FROM aws_project.finance_customer_data_stg AS c
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.customer_id = c.customer_id
# WHERE
#     a.acc_opening_date <= CURRENT_DATE - INTERVAL 5 YEAR;-- 12,192

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q4:
# 
# SELECT
#     currency_code,
#     SUM(CASE WHEN tran_status = 'TranStatus.C' THEN 1 ELSE 0 END) AS completed_count,
#     SUM(CASE WHEN tran_status = 'TranStatus.F' THEN 1 ELSE 0 END) AS failed_count
# FROM aws_project.finance_transaction_data_stg
# GROUP BY
#     currency_code
# ORDER BY
#     completed_count DESC,
#     failed_count DESC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT
#   DISTINCT tran_status
# FROM aws_project.finance_transaction_data_stg;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT
#   currency_code
#   , tran_status
#   , COUNT(tran_status)
# FROM aws_project.finance_transaction_data_stg
# GROUP BY
#   currency_code
#   , tran_status

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q5:
# 
# SELECT
#     t.transaction_id,
#     t.amount,
#     t.currency_code,
#     c.city,
#     c.country
# FROM aws_project.finance_transaction_data_stg AS t
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.account_id = t.src_account_id
# JOIN aws_project.finance_customer_data_stg AS c
#     ON c.customer_id = a.customer_id
# ORDER BY
#     t.amount DESC
# LIMIT
#     10;
# 
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT
#     DISTINCT ledger_type
# FROM aws_project.finance_ledger_data_stg;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q6(1):
# 
# SELECT
#     c.country,
#     SUM(l.amount) AS total_expenses
# FROM aws_project.finance_ledger_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.account_id = l.account_id
# JOIN aws_project.finance_customer_data_stg AS c
#     ON c.customer_id = a.customer_id
# WHERE
#     LOWER(l.ledger_type) = 'expense'
# GROUP BY
#     c.country
# ORDER BY
#     total_expenses DESC
# LIMIT
#     1;-- Belize

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q6(2):
# 
# SELECT
#     c.country,
#     SUM(l.amount) AS total_income
# FROM aws_project.finance_ledger_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.account_id = l.account_id
# JOIN aws_project.finance_customer_data_stg AS c
#     ON c.customer_id = a.customer_id
# GROUP BY
#     c.country
# ORDER BY
#     total_income DESC
# LIMIT
#     25;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q7:
# 
# SELECT
#     c.country,
#     COUNT(l.loan_id) AS total_loan_count,
#     SUM(l.principal_amount) AS total_principal_distributed
# FROM aws_project.finance_loan_data_stg AS l
# JOIN aws_project.finance_customer_data_stg AS c
#     ON c.customer_id = l.customer_id
# GROUP BY
#     c.country
# ORDER BY
#     total_principal_distributed DESC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q8:
# 
# SELECT
#     c.country,
#     COUNT(l.ledger_id) AS total_equity_count,
#     SUM(l.amount) AS total_equity
# FROM aws_project.finance_ledger_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.account_id = l.account_id
# JOIN aws_project.finance_customer_data_stg AS c
#     ON c.customer_id = a.customer_id
# WHERE
#     l.ledger_type = 'Equity'
# GROUP BY
#     c.country
# ORDER BY
#     total_equity DESC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Test
# 
# SELECT
#   DISTINCT country
# FROM aws_project.finance_customer_data_stg;-- 253

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Test
# 
# SELECT DISTINCT country
# FROM aws_project.finance_customer_data_stg
# WHERE country NOT IN (
#     SELECT DISTINCT c.country
#     FROM aws_project.finance_ledger_data_stg AS l
#     JOIN aws_project.finance_account_data_stg AS a
#         ON a.account_id = l.account_id
#     JOIN aws_project.finance_customer_data_stg AS c
#         ON c.customer_id = a.customer_id
#     WHERE LOWER(l.ledger_type) = 'equity'
# )
# ORDER BY country;-- 9

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q9:
# 
# WITH age_group_loan_counts AS (
#     SELECT
#         l.loan_id
#         , l.loan_type
#         , l.principal_amount
#         , CASE
#             WHEN DATE_DIFF('year', c.date_of_birth, CURRENT_DATE) BETWEEN 18 AND 25 THEN '18-25'
#             WHEN DATE_DIFF('year', c.date_of_birth, CURRENT_DATE) BETWEEN 26 AND 35 THEN '26-35'
#             WHEN DATE_DIFF('year', c.date_of_birth, CURRENT_DATE) BETWEEN 36 AND 45 THEN '36-45'
#             WHEN DATE_DIFF('year', c.date_of_birth, CURRENT_DATE) BETWEEN 46 AND 55 THEN '46-55'
#             WHEN DATE_DIFF('year', c.date_of_birth, CURRENT_DATE) > 55 THEN '55+'
#             ELSE 'Unknown/Other'
#         END AS age_group
#     FROM aws_project.finance_loan_data_stg AS l
#     JOIN aws_project.finance_customer_data_stg AS c
#         ON c.customer_id = l.customer_id
# )
# SELECT
#     age_group
#     , loan_type
#     , COUNT(*) AS total_loans_taken
#     , SUM(principal_amount) AS total_borrowed_volume
# FROM age_group_loan_counts
# GROUP BY
#     age_group
#     , loan_type
# ORDER BY
#     total_borrowed_volume DESC
# LIMIT
#     1;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# -- Q10:
# 
# SELECT
#     a.currency_code,
#     c.country,
#     COUNT(l.ledger_id) AS total_ledger_transactions,
#     SUM(l.amount) AS total_ledger_volume
# FROM aws_project.finance_ledger_data_stg AS l
# JOIN aws_project.finance_account_data_stg AS a
#     ON a.account_id = l.account_id
# JOIN aws_project.finance_customer_data_stg AS c
#     ON c.customer_id = a.customer_id
# GROUP BY
#     a.currency_code,
#     c.country
# ORDER BY
#     total_ledger_transactions DESC
# LIMIT
#     1;
#
