# -*- coding: utf-8 -*-
"""Financial Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/SOME_ID
"""

!pip install --upgrade gdrive

!pip install awscli boto3

from google.colab import drive
drive.mount('/content/drive')

!ls -lah /content/drive/MyDrive/

!mkdir /content/FinancialData

!find /content/drive/MyDrive/Data_Engg_Vol_1_2_Projects_Data/FinanceSystem_Dev_1_Dev_2/ -name "*.zip" -exec unzip -o {} -d /content/FinancialData \;

!rm -rf /content/FinancialData/__MACOSX/

!rsync  -ah --progress /content/FinancialData/ /content/drive/MyDrive/DuckDB/FinancialData/

!mkdir /content/DuckDB

# Commented out IPython magic to ensure Python compatibility.
# Install/update the necessary extensions
!pip install --quiet jupysql duckdb-engine

# Load the SQL extension and connect to DuckDB database
# %load_ext sql
# %config SqlMagic.autopandas = True
# %sql duckdb:////content/DuckDB/FinanceData.db

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext sql

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# CREATE SCHEMA aws_project;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# ROLLBACK;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# CREATE TABLE aws_project.finance_account_data_stg AS
# SELECT * FROM read_csv_auto('/content/FinancialData/finance_account_data/*.csv');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# CREATE TABLE aws_project.finance_customer_data_stg AS
# SELECT * FROM read_csv_auto('/content/FinancialData/finance_customer_data/*.csv');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# CREATE TABLE aws_project.finance_ledger_data_stg AS
# SELECT * FROM read_csv_auto('/content/FinancialData/finance_ledger_data/*.csv');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# CREATE TABLE aws_project.finance_loan_data_stg AS
# SELECT * FROM read_csv_auto('/content/FinancialData/finance_loan_data/*.csv');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# CREATE TABLE aws_project.finance_transaction_data_stg AS
# SELECT * FROM read_csv_auto('/content/FinancialData/finance_transaction_data/*.csv');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM duckdb_tables();

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM aws_project.finance_account_data_stg LIMIT 10;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM aws_project.finance_customer_data_stg LIMIT 10;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM aws_project.finance_ledger_data_stg LIMIT 10;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM aws_project.finance_loan_data_stg LIMIT 10;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM aws_project.finance_transaction_data_stg LIMIT 10;

!rsync -ah --progress /content/DuckDB/FinanceData.db /content/drive/MyDrive/DuckDB/FinancialData/
